name: suspect_library
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy=1.21
  - scipy=1.9.3
  - numba=0.55.1
  - llvmlite=0.38.*
  - sqlalchemy=1.4.*
  - certifi
  - joblib
  - jupyter
  - lxml
  - matplotlib
  - networkx
  - pyarrow
  - pyteomics
  - requests
  - seaborn
  - spectrum_utils
  - statsmodels
  - tqdm
  - streamlit